[package]
name = "gues_gaming"
version = "0.1.0"
authors = ["Rustam <rustam.osmanov.90@inbox.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand="0.4.6"
